---
language: ruby

branches:
  only:
    - master

script: bundle exec middleman build --verbose

rvm:
  - 2.0.0

env:
  global:
    - GIT_COMMITTER_NAME="Kouji Takao"
    - GIT_COMMITTER_EMAIL=kouji.takao@gmail.com
    - GIT_AUTHOR_NAME="Kouji Takao"
    - GIT_AUTHOR_EMAIL=kouji.takao@gmail.com
    - secure: "jCQvN2qMaOJIQqtfQQH/7Pi9X+66VZdzz4kd9fHrz8F1A8uApqtuxPG2kCQ4lpmYjFHaWM/8NtyZ3Vq3lS7U2pneMnkE0hXRRB0iRXfJxF+Cju2jhCwmEXteSKfVFB5q/fzbHjaxRVxdCqa7lTfh1ByJ/8G72VSzKNEnOjYsYQE="

before_script:
  - git clone --quiet https://github.com/smalruby/smalruby.github.com.git build

after_success:
  - [ "${TRAVIS_PULL_REQUEST}" = "true" ] && exit 0
  - cd build
  - git add -A
  - git commit -m 'Updated.'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/smalruby/smalruby.github.com.git master 2> /dev/null'
