---
language: ruby

branches:
  only:
    - master

script: bundle exec middleman build --verbose

rvm:
  - 2.3.5

env:
  global:
    - GIT_COMMITTER_NAME="Kouji Takao"
    - GIT_COMMITTER_EMAIL=kouji.takao@gmail.com
    - GIT_AUTHOR_NAME="Kouji Takao"
    - GIT_AUTHOR_EMAIL=kouji.takao@gmail.com

after_success:
  - git clone --quiet https://github.com/smalruby/smalruby.github.com.git
  - mv smalruby.github.com/.git build/
  - rm -rf smalruby.github.com
  - cd build
  - git add -A
  - git commit -m 'Updated.'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/smalruby/smalruby.github.com.git master 2> /dev/null'
